#!/usr/bin/env python3
"""Rebuild the photo gallery.

Adding new photos:

  1. Drop the full-size photos into  photos-inbox/
  2. Run                             python3 build-gallery.py
  3. Open photos.json, write a caption for each new photo
  4. Run it once more                python3 build-gallery.py

The script shrinks and rotates each photo, makes a thumbnail, and rewrites the
gallery block in photo.html. Your originals are copied to images-original/
before anything is changed, and nothing is ever deleted.
"""

import html
import json
import os
import re
import shutil
import subprocess
import sys

INBOX = "photos-inbox"
IMAGES = "images"
THUMBS = os.path.join(IMAGES, "thumbs")
ORIGINALS = "images-original"
MANIFEST = "photos.json"
PAGE = "photo.html"

# Full-size photos are capped at this; thumbnails in the grid at 500px.
FULL_MAX = 1600
THUMB_MAX = 500


def run(args):
    subprocess.run(args, check=True, capture_output=True)


def optimise(src, dest, max_edge, quality):
    """Rotate upright, shrink, strip metadata, save as progressive JPEG.

    -auto-orient must come before -strip, or the rotation is lost and photos
    come out sideways.
    """
    run(["convert", src, "-auto-orient", "-resize", f"{max_edge}x{max_edge}>",
         "-quality", str(quality), "-strip", "-interlace", "Plane", dest])


def dimensions(path):
    out = subprocess.run(["identify", "-format", "%w %h", path],
                         capture_output=True, text=True).stdout.split()
    return (out[0], out[1]) if len(out) == 2 else ("", "")


def import_inbox(manifest):
    """Bring any photos sitting in photos-inbox/ into the gallery."""
    if not os.path.isdir(INBOX):
        return manifest, []

    known = {entry["file"] for entry in manifest}
    added = []

    for name in sorted(os.listdir(INBOX)):
        if not name.lower().endswith((".jpg", ".jpeg", ".png", ".webp")):
            continue

        # Everything ends up as .jpg in images/
        stem = os.path.splitext(name)[0]
        target = stem + ".jpg"
        src = os.path.join(INBOX, name)

        if target in known:
            print(f"  skipping {name} - already in the gallery")
            continue

        os.makedirs(ORIGINALS, exist_ok=True)
        shutil.copy2(src, os.path.join(ORIGINALS, name))

        optimise(src, os.path.join(IMAGES, target), FULL_MAX, 82)
        optimise(os.path.join(IMAGES, target),
                 os.path.join(THUMBS, target), THUMB_MAX, 78)

        manifest.append({"file": target, "caption": ""})
        added.append(target)
        os.remove(src)
        print(f"  added {target}")

    return manifest, added


def build_markup(manifest):
    figures = []
    missing = []

    for index, entry in enumerate(manifest):
        full = os.path.join(IMAGES, entry["file"])
        thumb = os.path.join(THUMBS, entry["file"])

        if not os.path.exists(full):
            missing.append(entry["file"])
            continue
        if not os.path.exists(thumb):
            optimise(full, thumb, THUMB_MAX, 78)

        width, height = dimensions(thumb)
        caption = html.escape(entry.get("caption", ""), quote=True)

        figures.append(
            f'        <a class="shot" href="{full}" data-caption="{caption}" data-index="{index}">\n'
            # alt is empty on purpose: the caption below sits inside the same
            # link, so repeating it here makes a screen reader read every
            # photo's description twice.
            f'          <img src="{thumb}" width="{width}" height="{height}" '
            f'loading="lazy" decoding="async" alt="">\n'
            f'          <span class="shot-caption">{caption}</span>\n'
            f'        </a>'
        )

    return "\n".join(figures), missing


def main():
    for folder in (IMAGES, THUMBS):
        os.makedirs(folder, exist_ok=True)

    if not os.path.exists(MANIFEST):
        sys.exit(f"{MANIFEST} not found - run this from the site folder.")

    manifest = json.load(open(MANIFEST, encoding="utf-8"))

    print("Checking photos-inbox/ ...")
    manifest, added = import_inbox(manifest)

    json.dump(manifest, open(MANIFEST, "w", encoding="utf-8"),
              indent=2, ensure_ascii=False)

    markup, missing = build_markup(manifest)

    page = open(PAGE, encoding="utf-8").read()
    start, end = "<!-- GALLERY:START", "<!-- GALLERY:END -->"
    if start not in page or end not in page:
        sys.exit(f"Gallery markers missing from {PAGE} - cannot rebuild safely.")

    page = re.sub(
        re.escape(start) + r".*?" + re.escape(end),
        start + " - generated by build-gallery.py, do not edit by hand -->\n"
        + markup + "\n      " + end,
        page, flags=re.S)
    open(PAGE, "w", encoding="utf-8").write(page)

    print(f"\nGallery rebuilt: {len(manifest) - len(missing)} photos.")

    if missing:
        print("\nListed in photos.json but not found in images/:")
        for name in missing:
            print(f"  - {name}")

    blank = [e["file"] for e in manifest if not e.get("caption")]
    if blank:
        print(f"\n{len(blank)} photo(s) still need a caption in {MANIFEST}:")
        for name in blank:
            print(f"  - {name}")
        print("Add the captions, then run this script again.")


if __name__ == "__main__":
    main()
